### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by senthilkumar-1398** [wdtheprovider/in-app-purchases-subscription#11]
How to test live in app subscription without add licence testing in development?. I have already billing permission enable and release store in previous build. But I am not able to live test in subscription. Still i have Test mode.

**Comment by wdtheprovider** [comment]
Hi, You need to add your Gmail that you logged in with on your Play Store in your Phone to License Testing and also in Internal testing and join the testing program. 

Please check my detailed documentation here: https://dingi.icu/store/documentation/#config
