### ISSUE TITLE
I cannot get the items purchased check subscription in main activity when starts the app 

### ISSUE THREAD

**Issue by houssemmimoun27** [wdtheprovider/in-app-purchases-subscription#2]
billingClient = BillingClient.newBuilder(this).enablePendingPurchases().setListener((billingResult, list) -> {
        }).build();

        billingClient.startConnection(new BillingClientStateListener() {
            @Override
            public void onBillingServiceDisconnected() {

            }
            @Override
            public void onBillingSetupFinished(@NonNull BillingResult billingResult) {
                billingClient.queryPurchaseHistoryAsync(BillingClient.SkuType.SUBS, (billingResult1, list) -> {
                    if (billingResult1.getResponseCode() == BillingClient.BillingResponseCode.OK && list.size() > 0) {

                        int i = 0;
                        for (PurchaseHistoryRecord purchase: list) {
                            if(purchase.getSkus().get(i).equals("sub_monthly")) {
                                SharedPref.setIntInPref("premium", 1);
                                Toast.makeText(MainActivity.this, "You are a month premium user now", Toast.LENGTH_SHORT).show();

                            } else if (purchase.getSkus().get(i).equals("sub_yearly")) {
                                SharedPref.setIntInPref("premium", 1);
                                Toast.makeText(MainActivity.this, "You are a yearly premium user now", Toast.LENGTH_SHORT).show();

                            } 
                            else {
                                SharedPref.setIntInPref("premium", 0);
                                Toast.makeText(MainActivity.this, "You are not subscribed", Toast.LENGTH_SHORT).show();
                            }
                        }
                    } else if (list.size() == 0) {
                        SharedPref.setIntInPref("premium", 0);
                                Toast.makeText(MainActivity.this, "You are not subscribed", Toast.LENGTH_SHORT).show();
                    }
                });

            }
        });

**Comment by wdtheprovider** [comment]
The method to check purchased items(Subscriptions) is on the Splash screen not in the maintActivity
